apiVersion: v2
name: topology-builder
description: A Helm chart for Topology Builder application
type: application
version: 1.0.0
appVersion: '1.0.0'
keywords:
    - topology
    - network
    - diagram
maintainers:
    - name: Topology Builder Team
